{"bridge"
	{on "criticalhit" overload}
}

; Implementing mod scripts here.
(include "../manager/mod_script_1.inc")
(include "../manager/mod_script_2.inc")
(include "../manager/mod_script_3.inc")
(include "../manager/mod_script_4.inc")
(include "../manager/mod_script_5.inc")
(include "../manager/mod_script_6.inc")
(include "../manager/mod_script_7.inc")
(include "../manager/mod_script_8.inc")
(include "../manager/mod_script_9.inc")
(include "../manager/mod_script_10.inc")
(include "../manager/mod_script_11.inc")
(include "../manager/mod_script_12.inc")
(include "../manager/mod_script_13.inc")
(include "../manager/mod_script_14.inc")
(include "../manager/mod_script_15.inc")
(include "../manager/mod_script_16.inc")
(include "../manager/mod_script_17.inc")
(include "../manager/mod_script_18.inc")
(include "../manager/mod_script_19.inc")
(include "../manager/mod_script_20.inc")