{"windowed"
	{on "break_window" overload
		{if not effector "flamer_blocker"
			{if not "windows_broken"
				("try_break_window" args 0)		("try_break_window" args 1)
				("try_break_window" args 2)		("try_break_window" args 3)
				("try_break_window" args 4)		("try_break_window" args 5)
				("try_break_window" args 6)		("try_break_window" args 7)
				("try_break_window" args 8)		("try_break_window" args 9)
				("try_break_window" args 10)	("try_break_window" args 11)
				("try_break_window" args 12)	("try_break_window" args 13)
				("try_break_window" args 14)	("try_break_window" args 15)
				("try_break_window" args 16)	("try_break_window" args 17)
				("try_break_window" args 18)	("try_break_window" args 19)
				("try_break_window" args 20)	("try_break_window" args 21)
				("try_break_window" args 22)	("try_break_window" args 23)
			}
		}
	}
}